### ISSUE TITLE
[FEATURE] Refactor `maps.py`

### ISSUE THREAD

**Issue by TheGupta2012** [qBraid/pyqasm#98]
### Feature Description

The current `maps.py` file is ~1400 LOC. To improve maintainability, it will be good to separate it out into distinct modules.

### Implementation (Optional)

Logically distinct modules like - `maps/gates.py`, `maps/constants.py` and `maps/expressions.py`

**Comment by devilkiller-ag** [comment]
Hi @TheGupta2012, Can I work on this issue?

**Comment by TheGupta2012** [comment]
Sure, go ahead!

**Comment by devilkiller-ag** [comment]
Hi @TheGupta2012, I did the setup and explored the codebase. Before making the changes I wanted to confirm which functions have to be moved to which file. Here is what I have figured out yet:

`/src/pyqasm/map/gates.py`:
- u3_gate
- u3_inv_gate
- u2_gate
- u2_inv_gate
- global_phase_gate
- sxdg_gate_op
- cy_gate
- ch_gate
- xy_gate
- xx_plus_yy_gate
- ryy_gate
- zz_gate
- phaseshift_gate
- cswap_gate
- pswap_gate
- iswap_gate
- crx_gate
- cry_gate
- crz_gate
- cu_gate
- cu3_gate
- cu1_gate
- csx_gate
- rxx_gate
- rccx_gate
- rzz_gate
- cphaseshift_gate
- cphaseshift00_gate
- cphaseshift01_gate
- cphaseshift10_gate
- gpi_gate
- gpi2_gate
- ms_gate
- ccx_gate_op
- ecr_gate
- c3sx_gate
- c4x_gate
- prx_gate
- one_qubit_gate_op
- one_qubit_rotation_op
- two_qubit_gate_op

`/src/pyqasm/map/constants.py`:
- OPERATOR_MAP
- ONE_QUBIT_OP_MAP
- ONE_QUBIT_ROTATION_MAP
- TWO_QUBIT_OP_MAP
- THREE_QUBIT_OP_MAP
- FOUR_QUBIT_OP_MAP
- FIVE_QUBIT_OP_MAP
- SELF_INVERTING_ONE_QUBIT_OP_SET
- ST_GATE_INV_MAP
- ROTATION_INVERSION_ONE_QUBIT_OP_MAP
- U_INV_ROTATION_MAP
- LIMITS_MAP
- CONSTANTS_MAP
- VARIABLE_TYPE_MAP
- VARIABLE_TYPE_CAST_MAP
- ARRAY_TYPE_MAP
- MAX_ARRAY_DIMENSIONS
- SWITCH_BLACKLIST_STMTS
- SUPPORTED_QASM_VERSIONS
- QUANTUM_STATEMENTS

`/src/pyqasm/map/expressions.py`:
- qasm3_expression_op_map
- map_qasm_op_to_callable
- map_qasm_inv_op_to_callable
- qasm_variable_type_cast

Let me know if the segregation I have done is correct so that I can move forward with the task.

**Comment by TheGupta2012** [comment]
Hi @devilkiller-ag - 

1. Naming the folder as `maps` would be better
2. The segregation for `gates.py` should also include - 
- OPERATOR_MAP
- ONE_QUBIT_OP_MAP
- ONE_QUBIT_ROTATION_MAP
- TWO_QUBIT_OP_MAP
- THREE_QUBIT_OP_MAP
- FOUR_QUBIT_OP_MAP
- FIVE_QUBIT_OP_MAP
- SELF_INVERTING_ONE_QUBIT_OP_SET
- ST_GATE_INV_MAP
- ROTATION_INVERSION_ONE_QUBIT_OP_MAP
- U_INV_ROTATION_MAP

This is because if you add these in the `constants.py` file, it would greatly increase the size of the imports due to the fact that you will have to import every gate implementation from `gates.py`. Moreover, keeping the `map_qasm_op_to_callable` and `map_qasm_inv_op_to_callable` inside `gates.py` would make more sense as they are logically related to the gates. 

3. In similar fashion, every element related to expressions should be placed inside the `expressions`. Thus - 
- LIMITS_MAP
- CONSTANTS_MAP
- VARIABLE_TYPE_MAP
- VARIABLE_TYPE_CAST_MAP
- ARRAY_TYPE_MAP
- MAX_ARRAY_DIMENSIONS

should be moved to `expressions.py` 

Now that I think of it using a `constants.py` file might group unrelated constants together which we do not want. Better to just use `expressions.py` and `gates.py` for the segregration. For the - 

- SWITCH_BLACKLIST_STMTS
- SUPPORTED_QASM_VERSIONS
- QUANTUM_STATEMENTS

we can move them to the `__init__.py` file for the `maps`. This will allow us to do something like `from pyqasm.maps import QUANTUM_STATEMENTS` directly, without having a separate file for these constants.
